# Generated by Django 5.2.7 on 2025-11-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_student_tup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.TextField(blank=True, help_text='file in static/books/images/', max_length=64, null=True),
        ),
    ]
