# Generated by Django 5.2.7 on 2025-11-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.TextField(blank=True, help_text='file name in static/books/images/(bookcover.png/.jpeg)', max_length=64, null=True),
        ),
    ]
