# Generated by Django 5.2.7 on 2025-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, help_text='Full url to book cover', null=True),
        ),
    ]
