# Generated by Django 5.2.7 on 2025-11-26 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
